# Generated by Django 3.2.1 on 2021-08-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=3)),
        ),
        migrations.AddField(
            model_name='currencyrate',
            name='slug',
            field=models.SlugField(default=models.DateField()),
        ),
    ]
