# Generated by Django 3.2.1 on 2021-08-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210820_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyrate',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
