# Generated by Django 3.2.1 on 2021-08-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_currency_currencyrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='currencyrate',
            name='slug',
        ),
    ]
